[build]
  command = "npm run build:ssr"
  publish = "dist/angular-starter/browser"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/angular-starter/**"]

[[plugins]]
  package = "@netlify/angular-runtime"
